#ifndef CRYNU_CONFIG
#define CRYNU_CONFIG


#define I2C_DRIVER I2CD0

#define I2C1_SCL_PIN GP4
#define I2C1_SDA_PIN GP5


#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define SPI_MISO_PIN GP16

#define CIRQUE_PINNACLE_SPI_CS_PIN GP17


#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_1X
#define CIRQUE_PINNACLE_CURVED_OVERLAY
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

// #define WS2812_PIO_USE_PIO1
// #define WS2812_DI_PIN GP10
// #define RGB_MATRIX_LED_COUNT 16

/* Mechanical locking support. Use KC_LCAP, KC_LNUM or KC_LSCR instead in keymap */
// #define LOCKING_SUPPORT_ENABLE
/* Locking resynchronize hack */
// #define LOCKING_RESYNC_ENABLE

#endif
